name: "CI - Test Features"
on:
  pull_request:
    branches:
      - main
    paths:
      - src/**
      - test/**
      - "!**.md"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detect-changes:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    outputs:
      features: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            duckdb-cli: ./**/duckdb-cli/**
            go-task: ./**/go-task/**
            jq-likes: ./**/jq-likes/**
            julia: ./**/julia/**
            just: ./**/just/**
            mdbook: ./**/mdbook/**
            nushell: ./**/nushell/**

  test-detects:
    needs:
      - detect-changes
    runs-on: ubuntu-24.04${{  matrix.platform == 'arm64' && '-arm' || '' }}
    continue-on-error: true
    strategy:
      matrix:
        platform:
          - amd64
          - arm64
        features: ${{ fromJSON(needs.detect-changes.outputs.features) }}
        baseImage:
          - debian:stable-slim
          - ubuntu:jammy
          - ubuntu:noble
          - mcr.microsoft.com/devcontainers/base:ubuntu
          - mcr.microsoft.com/devcontainers/base:debian
    steps:
      - uses: actions/checkout@v4

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Generating tests for '${{ matrix.features }}' against '${{ matrix.baseImage }}'"
        run: devcontainer features test --skip-scenarios -f ${{ matrix.features }} -i ${{ matrix.baseImage }} .

  test-detectes-scenarios:
    if: ${{ github.event_name == 'pull_request' }}
    needs:
      - detect-changes
    runs-on: ubuntu-24.04${{  matrix.platform == 'arm64' && '-arm' || '' }}
    continue-on-error: true
    strategy:
      matrix:
        platform:
          - amd64
          - arm64
        features: ${{ fromJSON(needs.detect-changes.outputs.features) }}
    steps:
      - uses: actions/checkout@v4

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: Update scenarios.json if platform-specific scenarios exist
        run: |
          if [ -f "test/${{ matrix.features }}/scenarios-${{ matrix.platform }}-only.json" ]; then
            jq -s add 'test/${{ matrix.features }}/scenarios.json' 'test/${{ matrix.features }}/scenarios-${{ matrix.platform }}-only.json' >"/tmp/scenarios.json" && mv "/tmp/scenarios.json" "test/${{ matrix.features }}/scenarios.json"
          fi

      - name: "Generating tests for '${{ matrix.features }}' scenarios"
        run: devcontainer features test -f ${{ matrix.features }} --skip-autogenerated .

  test-all:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-24.04${{  matrix.platform == 'arm64' && '-arm' || '' }}
    continue-on-error: true
    strategy:
      matrix:
        platform:
          - amd64
          - arm64
        features:
          - duckdb-cli
          - go-task
          - jq-likes
          - julia
          - just
          - mdbook
          - nushell
        baseImage:
          - debian:stable-slim
          - ubuntu:jammy
          - ubuntu:noble
          - mcr.microsoft.com/devcontainers/base:ubuntu
          - mcr.microsoft.com/devcontainers/base:debian
    steps:
      - uses: actions/checkout@v4

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Generating tests for '${{ matrix.features }}' against '${{ matrix.baseImage }}'"
        run: devcontainer features test --skip-scenarios -f ${{ matrix.features }} -i ${{ matrix.baseImage }} .

  test-all-scenarios:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-24.04${{  matrix.platform == 'arm64' && '-arm' || '' }}
    continue-on-error: true
    strategy:
      matrix:
        platform:
          - amd64
          - arm64
        features:
          - duckdb-cli
          - go-task
          - jq-likes
          - julia
          - just
          - mdbook
          - nushell
    steps:
      - uses: actions/checkout@v4

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: Update scenarios.json if platform-specific scenarios exist
        run: |
          if [ -f "test/${{ matrix.features }}/scenarios-${{ matrix.platform }}-only.json" ]; then
            jq -s add 'test/${{ matrix.features }}/scenarios.json' 'test/${{ matrix.features }}/scenarios-${{ matrix.platform }}-only.json' >"/tmp/scenarios.json" && mv "/tmp/scenarios.json" "test/${{ matrix.features }}/scenarios.json"
          fi

      - name: "Generating tests for '${{ matrix.features }}' scenarios"
        run: devcontainer features test -f ${{ matrix.features }} --skip-autogenerated .

  test-global:
    runs-on: ubuntu-24.04${{  matrix.platform == 'arm64' && '-arm' || '' }}
    strategy:
      matrix:
        platform:
          - amd64
          - arm64
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Testing global scenarios"
        run: devcontainer features test --global-scenarios-only .
